### ISSUE TITLE
FragmentTesselator gone nuts

### ISSUE THREAD

**Issue by danirod** [Guerra24/Voxel#47] opened 2016-01-18 07:20 UTC
Can confirm FragmentTesselator is also broken on Windows.

**What happened**:

```
Fragment shader failed to compile with the following errors:
ERROR: 0:74: error(#160) Cannot convert from: "2-component vector of vec2" to: "highp float"
ERROR: error(#273) 1 compilation errors.  No code generated
Exception in thread "Voxel Main" java.lang.IllegalStateException: Syntax Error in FragmentTessellator.glsl
        at net.guerra24.voxel.client.graphics.shaders.ShaderProgram.loadShader(ShaderProgram.java:309)
        at net.guerra24.voxel.client.graphics.shaders.ShaderProgram.<init>(ShaderProgram.java:105)
        at net.guerra24.voxel.client.graphics.shaders.TessellatorShader.<init>(TessellatorShader.java:60)
        at net.guerra24.voxel.client.graphics.shaders.TessellatorShader.getInstance(TessellatorShader.java:39)
        at net.guerra24.voxel.client.resources.GameResources.init(GameResources.java:129)
        at net.guerra24.voxel.client.core.Voxel.init(Voxel.java:117)
        at net.guerra24.voxel.client.core.Voxel.mainLoop(Voxel.java:156)
        at net.guerra24.voxel.client.core.Voxel.<init>(Voxel.java:70)
        at net.guerra24.voxel.client.bootstrap.Bootstrap.main(Bootstrap.java:111)
 FAILED
```

**What should happen**:

The game should open.

**System specs**:
- OS: MS Windows 10
- CPU: Intel Xeon E5606
- Card: ATI Radeon HD 5400 Series
- RAM: 16 GB

**Comment by danirod** [comment] 2016-01-18 07:27
Quick workaround: commenting anything related to parallax on the shader code seems to do the trick again.

**Comment by Guerra24** [comment] 2016-01-18 20:47
Probably caused by NVIDIA cards compiling code correctly when has errors. I can't test it because im using NVIDIA.

**Comment by Guerra24** [comment] 2016-01-22 03:42
Temporally fixed by placing a "#define NVIDIA" on shader load and using "#ifdef NVIDIA" to check and compile if is valid.

**Closed as completed** 2016-04-05 00:58 UTC
Labels: problem:bug, type:rendering, platform:all
